CREATE DATABASE liadb
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE liadb;
CREATE TABLE Item (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    description VARCHAR(1000)
);

CREATE TABLE Origin (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(99) NOT NULL,
    description VARCHAR(1000) NOT NULL
);

CREATE TABLE Trait (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(99) NOT NULL,
    description VARCHAR(1000) NOT NULL
);
CREATE TABLE Champion (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
ultimateInfo VARCHAR(1000) NOT NULL,
cost INT NOT NULL,
recommendedItemIds VARCHAR(255),
originIds VARCHAR(255),
traitIds VARCHAR(255)
);

CREATE TABLE User (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL );